### ISSUE TITLE
Take this out and it looks nicer at the top of the outer thumb key

### ISSUE THREAD

**Issue by tleytek** [l4u/dactyl-manuform-mini-keyboard#1]
https://github.com/l4u/dactyl-manuform-mini-keyboard/blob/84e010318c51e4da334dc3d00b15a86116557ae5/src/dactyl_keyboard/dactyl.clj#L522

![scad](https://user-images.githubusercontent.com/32245655/41490709-490a2ff0-70c3-11e8-952e-758fe9030a90.png)

**Comment by l4u** [comment]
Thank you!! Great feedback! Fixed via https://github.com/l4u/dactyl-manuform-mini-keyboard/commit/5c851a324cf94f186060b55e425f5d06070cfdb7
