### ISSUE TITLE
How do you manage to hold the usb connector/TRRS jet in place?

### ISSUE THREAD

**Issue by klesh** [l4u/dactyl-manuform-mini-keyboard#3]
Hi, I love your work, as I examing the stl files. I'm confused  about the usb connector and TRRS jet. I can't see how they can be hold in place while plugging in....
Would you like to give me some insight? thanks.

**Comment by l4u** [comment]
The USB breakout board and TRRS jack are superglued to the case.

**Comment by klesh** [comment]
I see..
Thanks for the quick response! Appreciated.
