### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by matteslip** [l4u/dactyl-manuform-mini-keyboard#4]
Hi, i4u!
Could you share the firmware for your keyboard?
There are few changes regarding dactyl-manuform-keyboard, -1 one button, but it would be more convenient to have a ready-made firmware.
It could also be placed on https://config.qmk.fm
Thank you in advance!

**Comment by l4u** [comment]
Hi @matteslip The firmware will depend on how the actual wiring is done.

If you use the same wiring, you can use the original firmware for dactyl manuform but ignore/remove the extra key.

This repo contains only the case, but not the wiring.
